

### GET ALL TASKS
GET http://localhost:4000/api/


### CREATE TASK

POST http://localhost:4000/api/
Content-Type: application/json

{
    "title": "delete",
    "description": "myDescription",
    "status": false
}



### EDIT TASKS
PUT http://localhost:4000/api/eWZt57TWfXwPmmLNs4Ru
Content-Type: application/json

{
  "title": "updatedTitle123",
  "description": "updatedDescription"
}


### DELETE TASKS
DELETE http://localhost:4000/api/UPmD2RDoWbfx6Nf8WCSu
Content-Type: application/json


### UPDATE TASK STATUS

PATCH http://localhost:4000/api/eWZt57TWfXwPmmLNs4Ru
Content-Type: application/json