

### GET ALL TASKS
GET http://localhost:4000/api/



### EDIT TASKS
PATCH http://localhost:4000/api/
Content-Type: application/json

{
  "id": "dFQLjlvvR02iAa584pM6",
  "title": "updatedTitle",
  "description": "updatedDescription"
}


### CREATE TASK

POST http://localhost:4000/api/
Content-Type: application/json

{
    "title": "myTitle",
    "description": "myDescription"
}


### DELETE TASKS
DELETE http://localhost:4000/api/
Content-Type: application/json

{
    "id": "dFQLjlvvR02iAa584pM6"
}